all:compile

compile-lista:
	@gcc -o lista lista/*.c

compile:
	@gcc -o matriz matriz/*.c
	@gcc -o lista lista/*.c

compile-matriz:
	@gcc -o matriz matriz/*.c

run-matriz:
	./matriz.exe

run-lista:
	./lista.exe